spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/facturacion
    username: postgres
    password: 123
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
  application:
    name: product-service

server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
